version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0
  codecov: codecov/codecov@1.0.2

jobs:
  pytest:
    docker:
    - image: python:3.9.0
    environment:
      MONGO_USER_HOST: api.simon-park.codes
      MONGO_USER_PORT: 27017
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: pip install -r requirements.txt
    - run: python -m pip install --progress-bar=off pytest
    - run: python -m pytest test_codes/test.py

workflows:
  build:
    jobs:
      - cypress/cypress:
          yarn: true
      - pytest
      - codecov/coverage:
          token: 06232e08-caeb-4ebb-bf21-2f25e2dc5af3
