version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0
  codecov: codecov/codecov@1.1.3

jobs:
  pytest:
    docker:
    - image: python:3.9.0
    environment:
      MONGO_USER_HOST: api.simon-park.codes
      MONGO_USER_PORT: 27017
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: pip install -r requirements.txt
    - run: python -m pip install --progress-bar=off pytest
    - run: python -m pytest test_codes/test.py
    - codecov/upload:
        file: './coverage/clover.xml'
        token: d53c3d8a-0050-4a37-8c2e-d4aafa30b00a

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
      - pytest
